packageExtensions:
  "expo@51.0.27":
    peerDependencies:
      "@babel/preset-env": "*"
  "expo-router@*":
    peerDependencies:
      react: "*"
      react-native: "*"
      "expo-modules-autolinking": "*"
  "babel-preset-expo@11.0.14":
    dependencies:
      "@babel/core": "*"
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
  "jest-expo@51.0.3":
    dependencies:
      "@babel/core": "*"
    peerDependencies:
      jest: "*"
      react: "*"
  "@expo/cli@0.18.28":
    peerDependencies:
      expo-modules-autolinking: "*"
  "@react-native/babel-plugin-codegen@0.74.87":
    peerDependencies:
      "@babel/preset-env": "*"
  "babel-plugin-transform-flow-enums@0.0.2":
    peerDependencies:
      "@babel/core": "*"
  "expo-linking@6.3.1":
    peerDependencies:
      expo: "*"
  "expo-splash-screen@0.27.5":
    peerDependencies:
      expo-modules-autolinking: "*"
  "@react-native/babel-preset@0.74.87":
    peerDependencies:
      "@babel/preset-env": "*"
  "@react-native/metro-babel-transformer@0.74.87":
    peerDependencies:
      "@babel/preset-env": "*"
  "@react-native/community-cli-plugin@0.74.87":
    peerDependencies:
      "@babel/preset-env": "*"
  "greenfinger@*":
    peerDependencies:
      "@babel/preset-env": "*"
      "@react-native/normalize-colors": "*"
      expo-modules-autolinking: "*"
      react-test-renderer: "*"
  "react-native@0.74.5":
    peerDependencies:
      "@babel/preset-env": "*"