/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as http from "../http.js";
import type * as plants_createPlant from "../plants/createPlant.js";
import type * as plants_getAllPlants from "../plants/getAllPlants.js";
import type * as plants_index from "../plants/index.js";
import type * as users_getCurrentUser from "../users/getCurrentUser.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  http: typeof http;
  "plants/createPlant": typeof plants_createPlant;
  "plants/getAllPlants": typeof plants_getAllPlants;
  "plants/index": typeof plants_index;
  "users/getCurrentUser": typeof users_getCurrentUser;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
